/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as AffinityForTechnologyRouteImport } from './routes/affinity-for-technology'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as PathlessLayoutDashboardRouteImport } from './routes/_pathlessLayout/dashboard'
import { Route as PathlessLayoutChatRouteImport } from './routes/_pathlessLayout/chat'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const AffinityForTechnologyRoute = AffinityForTechnologyRouteImport.update({
  id: '/affinity-for-technology',
  path: '/affinity-for-technology',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutDashboardRoute = PathlessLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PathlessLayoutRoute,
} as any)
const PathlessLayoutChatRoute = PathlessLayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PathlessLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affinity-for-technology': typeof AffinityForTechnologyRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/scenario': typeof ScenarioRoute
  '/thanks': typeof ThanksRoute
  '/chat': typeof PathlessLayoutChatRoute
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affinity-for-technology': typeof AffinityForTechnologyRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/scenario': typeof ScenarioRoute
  '/thanks': typeof ThanksRoute
  '/chat': typeof PathlessLayoutChatRoute
  '/dashboard': typeof PathlessLayoutDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/affinity-for-technology': typeof AffinityForTechnologyRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/scenario': typeof ScenarioRoute
  '/thanks': typeof ThanksRoute
  '/_pathlessLayout/chat': typeof PathlessLayoutChatRoute
  '/_pathlessLayout/dashboard': typeof PathlessLayoutDashboardRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affinity-for-technology'
    | '/questionnaire'
    | '/scenario'
    | '/thanks'
    | '/chat'
    | '/dashboard'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affinity-for-technology'
    | '/questionnaire'
    | '/scenario'
    | '/thanks'
    | '/chat'
    | '/dashboard'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/affinity-for-technology'
    | '/questionnaire'
    | '/scenario'
    | '/thanks'
    | '/_pathlessLayout/chat'
    | '/_pathlessLayout/dashboard'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AffinityForTechnologyRoute: typeof AffinityForTechnologyRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ScenarioRoute: typeof ScenarioRoute
  ThanksRoute: typeof ThanksRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affinity-for-technology': {
      id: '/affinity-for-technology'
      path: '/affinity-for-technology'
      fullPath: '/affinity-for-technology'
      preLoaderRoute: typeof AffinityForTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/dashboard': {
      id: '/_pathlessLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathlessLayoutDashboardRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/_pathlessLayout/chat': {
      id: '/_pathlessLayout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof PathlessLayoutChatRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
  }
}

interface PathlessLayoutRouteChildren {
  PathlessLayoutChatRoute: typeof PathlessLayoutChatRoute
  PathlessLayoutDashboardRoute: typeof PathlessLayoutDashboardRoute
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutChatRoute: PathlessLayoutChatRoute,
  PathlessLayoutDashboardRoute: PathlessLayoutDashboardRoute,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AffinityForTechnologyRoute: AffinityForTechnologyRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ScenarioRoute: ScenarioRoute,
  ThanksRoute: ThanksRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
