/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeDashboardRouteImport } from './routes/prototype/dashboard'
import { Route as PrototypeChatRouteImport } from './routes/prototype/chat'
import { Route as ProjectsProjectNameRouteImport } from './routes/projects.$projectName'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeDashboardRoute = PrototypeDashboardRouteImport.update({
  id: '/prototype/dashboard',
  path: '/prototype/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeChatRoute = PrototypeChatRouteImport.update({
  id: '/prototype/chat',
  path: '/prototype/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectNameRoute = ProjectsProjectNameRouteImport.update({
  id: '/projects/$projectName',
  path: '/projects/$projectName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/scenario': typeof ScenarioRoute
  '/thanks': typeof ThanksRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectName': typeof ProjectsProjectNameRoute
  '/prototype/chat': typeof PrototypeChatRoute
  '/prototype/dashboard': typeof PrototypeDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/scenario': typeof ScenarioRoute
  '/thanks': typeof ThanksRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectName': typeof ProjectsProjectNameRoute
  '/prototype/chat': typeof PrototypeChatRoute
  '/prototype/dashboard': typeof PrototypeDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/scenario': typeof ScenarioRoute
  '/thanks': typeof ThanksRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectName': typeof ProjectsProjectNameRoute
  '/prototype/chat': typeof PrototypeChatRoute
  '/prototype/dashboard': typeof PrototypeDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/questionnaire'
    | '/scenario'
    | '/thanks'
    | '/api/chat'
    | '/projects/$projectName'
    | '/prototype/chat'
    | '/prototype/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/questionnaire'
    | '/scenario'
    | '/thanks'
    | '/api/chat'
    | '/projects/$projectName'
    | '/prototype/chat'
    | '/prototype/dashboard'
  id:
    | '__root__'
    | '/'
    | '/questionnaire'
    | '/scenario'
    | '/thanks'
    | '/api/chat'
    | '/projects/$projectName'
    | '/prototype/chat'
    | '/prototype/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ScenarioRoute: typeof ScenarioRoute
  ThanksRoute: typeof ThanksRoute
  ApiChatRoute: typeof ApiChatRoute
  ProjectsProjectNameRoute: typeof ProjectsProjectNameRoute
  PrototypeChatRoute: typeof PrototypeChatRoute
  PrototypeDashboardRoute: typeof PrototypeDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/dashboard': {
      id: '/prototype/dashboard'
      path: '/prototype/dashboard'
      fullPath: '/prototype/dashboard'
      preLoaderRoute: typeof PrototypeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/chat': {
      id: '/prototype/chat'
      path: '/prototype/chat'
      fullPath: '/prototype/chat'
      preLoaderRoute: typeof PrototypeChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectName': {
      id: '/projects/$projectName'
      path: '/projects/$projectName'
      fullPath: '/projects/$projectName'
      preLoaderRoute: typeof ProjectsProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ScenarioRoute: ScenarioRoute,
  ThanksRoute: ThanksRoute,
  ApiChatRoute: ApiChatRoute,
  ProjectsProjectNameRoute: ProjectsProjectNameRoute,
  PrototypeChatRoute: PrototypeChatRoute,
  PrototypeDashboardRoute: PrototypeDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
