[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pingouin>=0.5.5",
    "pyairtable>=3.3.0",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ruff>=0.15.2",
]
